version: '3.7'

services:

  sample:
    container_name: delopgave1_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/frontend-react'
      - '/frontend-react/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development