apiVersion: v1
kind: PersistentVolume
metadata: 
  name: delprojekt-sql-grp16
  namespace: "delprojekt-grp16"
spec: 
  storageClassName: fast
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"