apiVersion: v1
kind: Service
metadata:
  namespace: "delprojekt-grp16"
  name: delprojekt-sql-service-grp16
spec:
  selector:
    app: sql-grp16
  ports:
    - protocol: TCP
      port: 1401
      targetPort: 1401
  type: LoadBalancer